/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/isa-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Isa Codes */
        get: operations["get_isa_codes_isa_codes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/equipment-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Equipment Classes */
        get: operations["get_equipment_classes_equipment_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Projects */
        get: operations["read_projects_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project */
        get: operations["read_project_projects__project_id__get"];
        /** Update Project */
        put: operations["update_project_projects__project_id__put"];
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/diagrams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project Diagrams */
        get: operations["read_project_diagrams_projects__project_id__diagrams_get"];
        put?: never;
        /** Create Diagram */
        post: operations["create_diagram_projects__project_id__diagrams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagrams/{diagram_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Diagram */
        get: operations["read_diagram_diagrams__diagram_id__get"];
        /** Update Diagram */
        put: operations["update_diagram_diagrams__diagram_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagrams/{diagram_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Diagram */
        get: operations["export_diagram_diagrams__diagram_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Debug Validation Rules */
        get: operations["debug_validation_rules_validate_debug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Diagram */
        post: operations["validate_diagram_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/repair/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Repair Diagram */
        post: operations["repair_diagram_repair__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/layout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Layout Endpoint */
        post: operations["generate_layout_endpoint_generate_layout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/template": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Template Endpoint */
        post: operations["generate_template_endpoint_generate_template_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/repair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Auto Repair Endpoint */
        post: operations["auto_repair_endpoint_generate_repair_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/generate/ai-assist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Assist Endpoint */
        post: operations["ai_assist_endpoint_generate_ai_assist_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiAssistRequest */
        AiAssistRequest: {
            diagram: components["schemas"]["app__schemas__canonical__DiagramCanonical-Input"];
            /** Request */
            request: string;
        };
        /** AiAssistResponse */
        AiAssistResponse: {
            /** Suggestions */
            suggestions: {
                [key: string]: unknown;
            }[];
            /** Auto Applicable */
            auto_applicable: boolean;
            modified_diagram?: components["schemas"]["app__schemas__canonical__DiagramCanonical-Output"] | null;
        };
        /** CanonicalEdge */
        CanonicalEdge: {
            /** Id */
            id?: string;
            /** @default process */
            type: components["schemas"]["EdgeType"];
            /** From Node */
            from_node: string;
            /** From Port */
            from_port?: string | null;
            /** To Node */
            to_node: string;
            /** To Port */
            to_port?: string | null;
            /** Line Number */
            line_number?: string | null;
            /** Pipe Size */
            pipe_size?: string | null;
            /** Pipe Class */
            pipe_class?: string | null;
            /**
             * Insulation
             * @default N
             */
            insulation: string | null;
            properties?: components["schemas"]["EdgeProperties"];
            /** Waypoints */
            waypoints?: components["schemas"]["Position"][];
        };
        /** CanonicalNode */
        CanonicalNode: {
            /** Id */
            id?: string;
            type: components["schemas"]["NodeType"];
            /** Subtype */
            subtype: string;
            /** Tag */
            tag: string;
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            position: components["schemas"]["Position"];
            /**
             * Location
             * @default field
             */
            location: string | null;
            /** Properties */
            properties?: {
                [key: string]: unknown;
            };
            /** Nozzles */
            nozzles?: components["schemas"]["Nozzle"][];
        };
        /** Diagram */
        Diagram: {
            /** Name */
            name: string;
            /**
             * Diagram Type
             * @default PID
             */
            diagram_type: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Version */
            version: number;
            /** Status */
            status: string;
            /** Canonical Json */
            canonical_json: {
                [key: string]: unknown;
            };
            /** Canonical Schema Version */
            canonical_schema_version: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** DiagramCreate */
        DiagramCreate: {
            /** Name */
            name: string;
            /**
             * Diagram Type
             * @default PID
             */
            diagram_type: string;
            /** Canonical Json */
            canonical_json: {
                [key: string]: unknown;
            };
        };
        /** DiagramUpdate */
        DiagramUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Canonical Json */
            canonical_json?: {
                [key: string]: unknown;
            } | null;
        };
        /** EdgeProperties */
        EdgeProperties: {
            /** Size */
            size?: string | null;
            /** Spec */
            spec?: string | null;
            /** Insulation */
            insulation?: string | null;
            /** Fluid */
            fluid?: string | null;
            /** Temperature */
            temperature?: string | null;
            /** Pressure */
            pressure?: string | null;
        };
        /**
         * EdgeType
         * @enum {string}
         */
        EdgeType: "process" | "utility" | "signal_electrical" | "signal_pneumatic";
        /** GenerateLayoutRequest */
        GenerateLayoutRequest: {
            diagram: components["schemas"]["app__schemas__canonical__DiagramCanonical-Input"];
        };
        /** GenerateLayoutResponse */
        GenerateLayoutResponse: {
            diagram: components["schemas"]["app__schemas__canonical__DiagramCanonical-Output"];
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Template Type */
            template_type: string;
        };
        /** GenerateResponse */
        GenerateResponse: {
            diagram: components["schemas"]["app__schemas__canonical__DiagramCanonical-Output"];
            /** Template Type */
            template_type: string;
            /** Node Count */
            node_count: number;
            /** Edge Count */
            edge_count: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * NodeType
         * @enum {string}
         */
        NodeType: "equipment" | "valve" | "instrument" | "fitting";
        /** Nozzle */
        Nozzle: {
            /** Id */
            id?: string;
            /** Label */
            label: string;
            /** Side */
            side: string;
            /**
             * Offset
             * @default 0.5
             */
            offset: number;
        };
        /** Position */
        Position: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** Project */
        Project: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** RepairResponse */
        RepairResponse: {
            diagram: components["schemas"]["app__schemas__canonical__DiagramCanonical-Output"];
            /** Repairs */
            repairs: {
                [key: string]: unknown;
            }[];
            /** Remaining Violations */
            remaining_violations: components["schemas"]["Violation"][];
        };
        /** Rule */
        Rule: {
            /** Code */
            code: string;
            /** Category */
            category: string;
            /** Kind */
            kind: string;
            /** Scope */
            scope: string;
            /** Severity */
            severity?: string | null;
            /** Name Ko */
            name_ko: string;
            /** Name En */
            name_en?: string | null;
            /** Description */
            description?: string | null;
            /** Condition Json */
            condition_json?: unknown | null;
            /** Action Json */
            action_json?: unknown | null;
            /** Message Template */
            message_template?: string | null;
            /** Reference */
            reference?: string | null;
            /** Layer */
            layer: string;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Is Overridable
             * @default false
             */
            is_overridable: boolean;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /** Id */
            id: string;
            /** Ruleset Id */
            ruleset_id: string;
        };
        /** ValidateRequestPayload */
        ValidateRequestPayload: {
            diagram: components["schemas"]["app__schemas__canonical__DiagramCanonical-Input"];
            /** Ruleset Id */
            ruleset_id?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationReport */
        ValidationReport: {
            /** Passed */
            passed: boolean;
            /** Error Count */
            error_count: number;
            /** Warning Count */
            warning_count: number;
            /** Violations */
            violations: components["schemas"]["Violation"][];
        };
        /** Violation */
        Violation: {
            /** Rule Code */
            rule_code: string;
            /** Severity */
            severity: string;
            /** Message */
            message: string;
            /** Node Id */
            node_id?: string | null;
            /** Edge Id */
            edge_id?: string | null;
        };
        /** RepairRequest */
        app__api__repair__RepairRequest: {
            canonical_json: components["schemas"]["app__schemas__project__DiagramCanonical"];
            /** Repairs */
            repairs: {
                [key: string]: unknown;
            }[];
        };
        /**
         * DiagramCanonical
         * @description 단일 P&ID 도면의 Canonical 표현. DB 저장 기준.
         */
        "app__schemas__canonical__DiagramCanonical-Input": {
            /**
             * Canonical Schema Version
             * @default 1
             */
            canonical_schema_version: number;
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /**
             * Diagram Type
             * @default pid
             */
            diagram_type: string;
            /** Project Id */
            project_id?: string | null;
            /** Nodes */
            nodes?: components["schemas"]["CanonicalNode"][];
            /** Edges */
            edges?: components["schemas"]["CanonicalEdge"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * DiagramCanonical
         * @description 단일 P&ID 도면의 Canonical 표현. DB 저장 기준.
         */
        "app__schemas__canonical__DiagramCanonical-Output": {
            /**
             * Canonical Schema Version
             * @default 1
             */
            canonical_schema_version: number;
            /** Id */
            id?: string;
            /** Name */
            name: string;
            /**
             * Diagram Type
             * @default pid
             */
            diagram_type: string;
            /** Project Id */
            project_id?: string | null;
            /** Nodes */
            nodes?: components["schemas"]["CanonicalNode"][];
            /** Edges */
            edges?: components["schemas"]["CanonicalEdge"][];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** RepairRequest */
        app__schemas__generator_models__RepairRequest: {
            diagram: components["schemas"]["app__schemas__canonical__DiagramCanonical-Input"];
            /** Violations */
            violations: components["schemas"]["Violation"][];
        };
        /** DiagramCanonical */
        app__schemas__project__DiagramCanonical: {
            /**
             * Canonical Schema Version
             * @default 1
             */
            canonical_schema_version: number;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            } | null;
            /**
             * Nodes
             * @default []
             */
            nodes: {
                [key: string]: unknown;
            }[];
            /**
             * Edges
             * @default []
             */
            edges: {
                [key: string]: unknown;
            }[];
            /**
             * Signal Lines
             * @default []
             */
            signal_lines: {
                [key: string]: unknown;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_isa_codes_isa_codes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    get_equipment_classes_equipment_classes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rule"][];
                };
            };
        };
    };
    read_projects_projects_get: {
        parameters: {
            query?: {
                skip?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_project_diagrams_projects__project_id__diagrams_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagram"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_diagram_projects__project_id__diagrams_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagramCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagram"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_diagram_diagrams__diagram_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diagram_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagram"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_diagram_diagrams__diagram_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diagram_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagramUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagram"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_diagram_diagrams__diagram_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                diagram_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    debug_validation_rules_validate_debug_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    validate_diagram_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidateRequestPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    repair_diagram_repair__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__api__repair__RepairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["app__schemas__project__DiagramCanonical"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_layout_endpoint_generate_layout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateLayoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateLayoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_template_endpoint_generate_template_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenerateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auto_repair_endpoint_generate_repair_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["app__schemas__generator_models__RepairRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RepairResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_assist_endpoint_generate_ai_assist_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiAssistRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiAssistResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
